const AdminActions = {
  FETCH_LIST_BUSSINESS_OWNER: "FETCH_LIST_BUSSINESS_OWNER",
  FETCH_LIST_BUSSINESS_OWNER_SUCCESS: "FETCH_LIST_BUSSINESS_OWNER_SUCCESS",

  TOGGLE_ACCOUNT_STATUS: 'TOGGLE_ACCOUNT_STATUS',
  TOGGLE_ACCOUNT_STATUS_SUCCESS: 'TOGGLE_ACCOUNT_STATUS_SUCCESS'
};

export default AdminActions;
