const CustomerActions = {
  FETCH_LIST_CUSTOMER: "FETCH_LIST_CUSTOMER",
  FETCH_LIST_CUSTOMER_SUCCESS: "FETCH_LIST_CUSTOMER_SUCCESS",

  GET_CUSTOMER: "GET_CUSTOMER",
  GET_CUSTOMER_SUCCESS: "GET_CUSTOMER_SUCCESS",

  CREATE_CUSTOMER: "CREATE_CUSTOMER",
  CREATE_CUSTOMER_SUCCESS: "CREATE_CUSTOMER_SUCCESS",

  DELET_CUSTOMER: "DELET_CUSTOMER",
  DELET_CUSTOMER_SUCCESS: "DELET_CUSTOMER_SUCCESS",
};


export default CustomerActions;
