const ChatActions = {
  FETCH_MESSAGES: 'FETCH_MESSAGES',
  FETCH_MESSAGES_SUCCESS: 'FETCH_MESSAGES_SUCCESS',
  FETCH_MESSAGES_FAILURE: 'FETCH_MESSAGES_FAILURE',

  SEND_MESSAGE: 'SEND_MESSAGE',
  SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',

  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
  RECEIVE_MESSAGE_SUCCESS: 'RECEIVE_MESSAGE_SUCCESS',
  RECEIVE_MESSAGE_FAILURE: 'RECEIVE_MESSAGE_FAILURE',

  FETCH_CHAT_LIST: "FETCH_CHAT_LIST",
  FETCH_CHAT_LIST_SUCCESS: "FETCH_CHAT_LIST_SUCCESS", 
  FETCH_CHAT_LIST_FAILURE: "FETCH_CHAT_LIST_FAILURE",
};

export default ChatActions;
