const TransactionActions = {
  FETCH_LIST_TRANSACTION: "FETCH_LIST_TRANSACTION",
  FETCH_LIST_TRANSACTION_SUCCESS: "FETCHFETCH_LIST_TRANSACTION_SUCCESS_LIST_CUSTOMER_SUCCESS",

  GET_TRANSACTION: "GET_TRANSACTION",
  GET_TRANSACTION_SUCCESS: "GET_TRANSACTION_SUCCESS",

  CREATE_TRANSACTION: "CREATE_TRANSACTION",
  CREATE_TRANSACTION_SUCCESS: "CREATE_TRANSACTION_SUCCESS",

  DELETE_TRANSACTION: "DELETE_TRANSACTION",
  DELETE_TRANSACTION_SUCCESS: "DELETE_TRANSACTION_SUCCESS",

};


export default TransactionActions;
