const UserActions = {
  UPDATE_INFORMATION: 'UPDATE_INFORMATION',
  UPDATE_INFORMATION_SUCCESS: 'UPDATE_INFORMATION_SUCCESS',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
};
export default UserActions;
