const PROFILE_SCREEN= 'PROFILE_SCREEN';
const PASSWORD_SCREEN= 'PASSWORD_SCREEN';
const PROFILE= 'PROFILE';
const CUSTOMER_LIST= 'CUSTOMER_LIST';
const CREATE_CUSTOMER= 'CREATE_CUSTOMER';
const CUSTOMER_DETAIL= 'CUSTOMER_DETAIL';
const BUSINESS_DASHBOARD= 'BUSINESS_DASHBOARD';
export {
  PROFILE_SCREEN,
  PASSWORD_SCREEN,
  PROFILE,
  CUSTOMER_LIST,
  CREATE_CUSTOMER,
  CUSTOMER_DETAIL,
  BUSINESS_DASHBOARD,
}